create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  task_key text unique not null,
  title text not null,
  description text default '',
  status text not null default 'TODO' check (status in ('TODO','IN_PROGRESS','DONE')),
  priority text not null default 'MEDIUM' check (priority in ('LOW','MEDIUM','HIGH','CRITICAL')),
  assignee_id bigint references public.users(id) on delete set null,
  due_date date,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

insert into public.users (name,email) values
('Sai','sai@team.local'),
('John','john@team.local'),
('Alex','alex@team.local'),
('Mike','mike@team.local'),
('Sarah','sarah@team.local')
on conflict (email) do nothing;

alter table public.users enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "team users read" on public.users;
create policy "team users read" on public.users for select using (true);

drop policy if exists "team tasks read" on public.tasks;
create policy "team tasks read" on public.tasks for select using (true);

drop policy if exists "team tasks insert" on public.tasks;
create policy "team tasks insert" on public.tasks for insert with check (true);

drop policy if exists "team tasks update" on public.tasks;
create policy "team tasks update" on public.tasks for update using (true) with check (true);

drop policy if exists "team tasks delete" on public.tasks;
create policy "team tasks delete" on public.tasks for delete using (true);

-- Enable realtime for collaborative updates.
alter publication supabase_realtime add table public.tasks;
